"""rename cpf to cnpj for profissionais

Revision ID: 123456789abc
Revises:
Create Date: 2024-07-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123456789abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               new_column_name='cnpj',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               new_column_name='cpf',
               existing_nullable=True)

    # ### end Alembic commands ###