[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_[slug]_%(rev_id)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .
version_path_separator = ;

# The set of implementations specified by sqlalchemy.url may be used
# to set the sqlalchemy.url in alembic.ini and/or env.py.
# This allows different URLs to be used depending on the context,
# e.g. one for a developer's system, one for integration testing,
# one for staging, and one for production.
sqlalchemy.url = mariadb+mariadbconnector://root:I1e1l2@127.0.0.1:3306/tcc

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_general]
format = %(levelname)-5.5s [%(name)s] %(message)s
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(asctime)s %(message)s